name: test-trader
services:
  ib-gateway:
    restart: unless-stopped
    build:
      context: ./stable
      tags:
        - "ghcr.io/gnzsnz/ib-gateway:10.37.1l"
    image: ghcr.io/gnzsnz/ib-gateway:10.37.1l
    environment:
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD_FILE: /run/secrets/tws_password
      TRADING_MODE: ${TRADING_MODE:-paper}
      READ_ONLY_API: ${READ_ONLY_API:-}
      TWOFA_TIMEOUT_ACTION: ${TWOFA_TIMEOUT_ACTION:-exit}
      AUTO_RESTART_TIME: ${AUTO_RESTART_TIME:-}
      RELOGIN_AFTER_TWOFA_TIMEOUT: ${RELOGIN_AFTER_TWOFA_TIMEOUT:-no}
      TWOFA_EXIT_INTERVAL: ${TWOFA_EXIT_INTERVAL:-60}
      TIME_ZONE: ${TIME_ZONE:-Etc/UTC}
      BYPASS_WARNING: yes
    secrets:
      - tws_password
    ports:
      - "127.0.0.1:4001:4003"
      - "127.0.0.1:4002:4004"
secrets:
  tws_password:
    file: ./pass/tws_password.txt
